const platformOptions: string[] = ['all', 'pc', 'browser'];

const sortOptions: string[] = [
  'relevance',
  'alphabetical',
  'release-date',
  'popularity',
];

const categoryOptions: string[] = [
  'all',
  'mmorpg',
  'shooter',
  'strategy',
  'moba',
  'racing',
  'sports',
  'social',
  'sandbox',
  'open world',
  'survival',
  'pvp',
  'pve',
  'pixel',
  'voxel',
  'zombie',
  'turn based',
  'first person',
  'third person',
  'top-down',
  'tank',
  'space',
  'sailing',
  'side-scroller',
  'superhero',
  'permadeath',
  'card',
  'battle royale',
  'mmo',
  'mmofps',
  'mmotps',
  '3d',
  '2d',
  'anime',
  'fantasy',
  'sci-fi',
  'fighting',
  'action rpg',
  'action',
  'military',
  'martial arts',
  'flight',
  'low-spec',
  'tower defense',
  'horror',
  'mmorts',
];

export default { platformOptions, sortOptions, categoryOptions};